# -*- coding: utf-8 -*-
"""Generate the standalone sources from the Windhawk mod.

The mod file stays the single source of truth: this script strips the Windhawk
tool-mod bootstrap (which only exists to spawn a host process and hook its
entry point — a standalone .exe is that host) and turns the settings block into
compiled-in defaults.

Run it again after editing the mod to re-sync.
"""
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.join(HERE, "..", "dynamic-island-for-windows.wh.cpp")
CRLF = "\r\n"

# Everything from this comment to the end of the file is Windhawk plumbing.
BOOTSTRAP_MARKER = "// Windhawk tool mod implementation for mods which don't need to inject"

# Defined by the bootstrap; nothing above it may use them.
BOOTSTRAP_SYMBOLS = [
    "g_isToolModProcessLauncher",
    "g_toolModProcessMutex",
    "EntryPoint_Hook",
    "WH_MOD_ID",
    "Wh_SetFunctionHook",
]


def parse_settings(block):
    """Flatten the mod's YAML settings block into Group.Key -> default."""
    defaults = []
    group = None
    for line in block.split("\n"):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        # "- Appearance:" opens a group.
        m = re.match(r"^- (\w+):\s*$", line)
        if m:
            group = m.group(1)
            continue
        # "  - Key: value" is a setting inside the current group.
        m = re.match(r"^  - (\w+):\s*(.*)$", line)
        if m and group:
            key, value = m.group(1), m.group(2).strip()
            if value.startswith(("'", '"')) and value.endswith(("'", '"')):
                value = value[1:-1]
            defaults.append((group + "." + key, value))
    return defaults


def cpp_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    src = io.open(MOD, encoding="utf-8", newline=None).read()

    cut = src.index(BOOTSTRAP_MARKER)
    body = src[:cut]

    for sym in BOOTSTRAP_SYMBOLS:
        if sym in body:
            sys.exit("error: %s is used above the bootstrap; cannot strip it" % sym)

    for entry in ["WhTool_ModInit", "WhTool_ModSettingsChanged", "WhTool_ModUninit"]:
        if entry not in body:
            sys.exit("error: %s not found in the mod body" % entry)

    settings_block = src[src.index("==WindhawkModSettings=="):
                         src.index("==/WindhawkModSettings==")]
    defaults = parse_settings(settings_block)
    if not defaults:
        sys.exit("error: no settings parsed")

    header = (
        "// Generated by gen_island.py from ../dynamic-island-for-windows.wh.cpp\n"
        "// Do not edit: change the mod and run the generator again.\n\n"
    )

    io.open(os.path.join(HERE, "island.cpp"), "w", encoding="utf-8",
            newline=CRLF).write(header + body)

    lines = [header, "// Defaults taken from the mod's own settings block.\n",
             "static const SettingDefault kSettingDefaults[] = {\n"]
    for key, value in defaults:
        lines.append('    {L"%s", L"%s"},\n' % (cpp_escape(key), cpp_escape(value)))
    lines.append("};\n")
    io.open(os.path.join(HERE, "settings_defaults.inc"), "w", encoding="utf-8",
            newline=CRLF).write("".join(lines))

    print("island.cpp:            %d lines (bootstrap stripped: %d)"
          % (body.count("\n") + 1, src.count("\n") - body.count("\n")))
    print("settings_defaults.inc: %d settings" % len(defaults))


if __name__ == "__main__":
    main()
